version: 2
updates:
- package-ecosystem: docker
  directory: "/tipping"
  schedule:
    interval: monthly
  open-pull-requests-limit: 25
- package-ecosystem: npm
  directory: "/tipping"
  schedule:
    interval: monthly
  open-pull-requests-limit: 25
- package-ecosystem: pip
  directory: "/tipping"
  schedule:
    interval: weekly
    day: wednesday
  open-pull-requests-limit: 25
- package-ecosystem: npm
  directory: "/browser_test"
  schedule:
    interval: weekly
    day: sunday
  open-pull-requests-limit: 25
- package-ecosystem: docker
  directory: "/backend"
  schedule:
    interval: monthly
  open-pull-requests-limit: 25
  ignore:
  - dependency-name: python
    versions:
    - "> 3.8.1.pre.slim.pre.buster"
    - "< 3.9"
- package-ecosystem: docker
  directory: "/frontend"
  schedule:
    interval: monthly
  open-pull-requests-limit: 25
  ignore:
  - dependency-name: node
    versions:
    - "> 13.5.0.pre.buster.pre.slim"
    - "< 13.6"
- package-ecosystem: pip
  directory: "/backend"
  schedule:
    interval: weekly
    day: monday
  open-pull-requests-limit: 25
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: weekly
    day: friday
  open-pull-requests-limit: 25
