version: "3.2"
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    depends_on:
      - db
      - data_science
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings.development
      - DATABASE_HOST=db
      - GRAPHIQL=True
    command: ./scripts/wait-for-it.sh data_science:8008 -- python3 manage.py runserver 0.0.0.0:8000
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: yarn start
  storybook:
    image: tipresias_frontend:latest
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "3333:3333"
    command: yarn run storybook -h 0.0.0.0 -p 3333 --quiet
  data_science:
    image: cfranklin11/tipresias_data_science:latest
    volumes:
      - ./data_science/data:/app/data
    ports:
      - "8008:8008"
    stdin_open: true
    tty: true
    depends_on:
      - afl_data
    env_file: .env
    environment:
      - PYTHON_ENV=development
      - PYTHONPATH=./src
    command: python3 app.py
  afl_data:
    image: cfranklin11/tipresias_afl_data:latest
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    command: Rscript app.R
  db:
    image: postgres:11.6
    environment:
      - POSTGRES_DB=tipresias
  browser_test:
    build: ./browser_test
    depends_on:
      - frontend
    volumes:
      - ./browser_test/cypress:/app/cypress
      - ./browser_test/cypress.json:/app/cypress.json
    # Need to use 'host' network mode to avoid cross-host errors
    # from Webpack server
    network_mode: "host"
volumes:
  node_modules:
    external: true
