version: "3.2"
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
      - ./data:/app/data
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    depends_on:
      - db
      - afl_data
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings.development
      - DATABASE_HOST=db
      - GRAPHIQL=True
    command: python3 manage.py runserver 0.0.0.0:8000
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: yarn start
  data_science:
    build: ./data_science
    volumes:
      - ./data_science:/app
      - ./data:/app/data
    ports:
      - "8008:8008"
    stdin_open: true
    tty: true
    depends_on:
      - afl_data
    env_file: .env
    environment:
      - PYTHON_ENV=development
  afl_data:
    build: ./afl_data
    volumes:
      - ./afl_data:/app/afl_data
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    command: Rscript app.R
  notebook:
    image: tipresias_data_science:latest
    volumes:
      - ./data_science:/app
      - ./data:/app/data
    ports:
      - "8888:8888"
    depends_on:
      - data_science
    command: jupyter notebook --ip 0.0.0.0 --no-browser --allow-root
  db:
    image: postgres
    environment:
      - POSTGRES_DB=tipresias
  browser_test:
    build: ./browser_test
    depends_on:
      - frontend
    volumes:
      - ./browser_test/cypress:/app/cypress
      - ./browser_test/cypress.json:/app/cypress.json
    # Need to use 'host' network mode to avoid cross-host errors
    # from Webpack server
    network_mode: "host"
volumes:
  node_modules:
    external: true
