version: "3.2"
services:
  app:
    image: cfranklin11/tipresias_backend:latest
    ports:
      - "80:80"
    stdin_open: true
    tty: true
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings.production
      - DATABASE_NAME=${DATABASE_NAME}
    command: gunicorn -b 0.0.0.0:80 -w 3 -t 1200 --access-logfile=- project.wsgi
