version: "3.2"
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
      - ./data:/app/data
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    depends_on:
      - db
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings.development
      - DATABASE_HOST=db
      - GRAPHIQL=True
    command: python3 manage.py runserver 0.0.0.0:8000
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: yarn start
  notebook:
    image: tipresias_backend:latest
    volumes:
      - ./backend:/app/backend
      - ./data:/app/data
    ports:
      - "8888:8888"
    depends_on:
      - backend
    command: jupyter notebook --ip 0.0.0.0 --no-browser --allow-root
  db:
    image: postgres
    environment:
      - POSTGRES_DB=tipresias
