version: "3.2"
services:
  backend:
    image: cfranklin11/tipresias_server:master
    volumes:
      - ./backend:/app/backend
      - ./data:/app/data
    ports:
      - "8000:8000"
    depends_on:
      - db
      - afl_data
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings.development
      - DATABASE_HOST=db
      - EMAIL_RECIPIENT=test@test.com
      - SENDGRID_API_KEY=test
    command: python3 manage.py runserver 0.0.0.0:8000
  afl_data:
    image: cfranklin11/tipresias_afl_data:latest
    volumes:
      - ./afl_data:/app/afl_data
    ports:
      - "8080:8080"
    command: Rscript app.R
  frontend:
    image: cfranklin11/tipresias_client:master
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CI=true
    depends_on:
      - backend
    command: yarn start
  db:
    image: postgres
    environment:
      - POSTGRES_DB=tipresias
  browser_test:
    image: cfranklin11/tipresias_browser_test:latest
    depends_on:
      - frontend
    volumes:
      - ./browser/cypress:/app/cypress
      - ./browser/cypress.json:/app/cypress.json
    # Need to use 'host' network mode to avoid cross-host errors
    # from Webpack server
    network_mode: "host"
