version: "3.2"
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    depends_on:
      - db
      - splash
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-project.settings.development}
      - DATABASE_HOST=db
      - DATABASE_NAME=${DATABASE_NAME:-tipresias}
      - GRAPHIQL=True
    command: python3 manage.py runserver 0.0.0.0:8000
  tipping:
    build: ./tipping
    command: npm start
    depends_on:
      - backend
      - faunadb
    env_file: .env
    environment:
      PYTHONPATH: "./src"
      PORT: 3333
      DATABASE_HOST: faunadb:8443
      DATA_SCIENCE_SERVICE: http://host.docker.internal:8008
      TIPRESIAS_APP: http://backend:8000
      AWS_SHARED_CREDENTIALS_FILE: .aws/credentials
      ROLLBAR_TOKEN: rollbar_token
      FAUNA_SCHEME: http
    ports:
      - "3333:3333"
    stdin_open: true
    tty: true
    volumes:
      - ./tipping:/app
      - /app/node_modules
      - ${HOME}/.aws:/app/.aws
  db:
    image: postgres:11.6
    environment:
      - POSTGRES_DB=$DATABASE_NAME
    ports:
      - "5432:5432"
  faunadb:
    image: fauna/faunadb:latest
    ports:
      - "8443:8443" # Base API
      - "8084:8084" # GQL Api
  splash:
    image: scrapinghub/splash
    ports:
      - "8050:8050"
  graphql_inspector:
    image: kamilkisiela/graphql-inspector
    volumes:
      - ./backend/server:/app
    command: graphql-inspector diff schema.graphql new.graphql
