version: "3.2"
services:
  backend:
    image: cfranklin11/tipresias_backend:latest
    ports:
      - "8000:8000"
    depends_on:
      - db
      - data_science
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings.development
      - DATABASE_HOST=db
      - EMAIL_RECIPIENT=test@test.com
      - SENDGRID_API_KEY=test
      - CI=true
    command: ./scripts/wait-for-it.sh data_science:8008 -- python3 manage.py runserver 0.0.0.0:8000
  data_science:
    image: cfranklin11/tipresias_data_science:latest
    ports:
      - "8008:8008"
    depends_on:
      - afl_data
    environment:
      - PYTHON_ENV=development
    command: python3 app.py
  afl_data:
    image: cfranklin11/tipresias_afl_data:latest
    ports:
      - "8080:8080"
    command: Rscript app.R
  frontend:
    image: cfranklin11/tipresias_frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CI=true
    depends_on:
      - backend
    command: yarn start
  db:
    image: postgres
    environment:
      - POSTGRES_DB=tipresias
  browser_test:
    image: cfranklin11/tipresias_browser_test:latest
    depends_on:
      - frontend
    # Need to use 'host' network mode to avoid cross-host errors
    # from Webpack server
    network_mode: "host"
