version: "3.2"

services:
  app:
    image: cfranklin11/tipresias_app:latest
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    depends_on:
      - db
      - afl_data
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings.production
      - DATABASE_HOST=db
      - NODE_ENV=production
      - PRODUCTION_HOST=104.248.155.53
    networks:
      - webnet
    restart: unless-stopped
    command: python3 ./backend/manage.py runserver 0.0.0.0:8000
  afl_data:
    image: cfranklin11/tipresias_afl_data:latest
    stdin_open: true
    tty: true
    networks:
      - webnet
    restart: unless-stopped
    command: Rscript app.R
  db:
    image: postgres
    environment:
      - POSTGRES_DB=tipresias
    networks:
      - webnet
    restart: unless-stopped

networks:
  webnet:
    driver: bridge
